### ISSUE TITLE
Ignore miner transactions

### ISSUE THREAD

**Issue by ngthanhtrung** [ethgasstation/ethgasstation-backend#16]
Miners sometimes include their own transactions in their mined blocks. Those transactions should be excluded so the hashpower acceptance would be more accurate. Normally those transactions have gas price of 1 Gwei.

**Comment by ethgasstation** [comment]
Yes- this is a good point - but this is more of an issue for the express oracle - will consider for here too

**Comment by ethgasstation** [comment]
Completed
