### ISSUE TITLE
ImportError: No module named 'colored'

### ISSUE THREAD

**Issue by Alex314Ru** [ethgasstation/ethgasstation-backend#18]
`colored==1.3.5` package is missing in [requirements.txt](https://github.com/ethgasstation/ethgasstation-backend/blob/master/requirements.txt), and when you're trying to run this app as a Docker container, it says `ImportError: No module named 'colored'`.

**Comment by 10a7** [comment]
Thanks! We're not running the Dockerized version at the moment in prod, so if you see anything not working, please submit a pull request.
