### ISSUE TITLE
website shows raw PHP

### ISSUE THREAD

**Issue by maaktweluit** [ethgasstation/ethgasstation-backend#23]
Hi EthGasStation!

This morning i noticed your website (http://ethgasstation.info/) only shows the PHP code, hope you can find the issue and fix it soon.
I notice it works on https:// maybe you can make a forced redirect from http to https

Thank you for making this awesome website!

**Comment by owocki** [comment]
i see this also @ethgasstation 

http://bits.owocki.com/2l01350C3J2s/Screen%20Shot%202018-06-11%20at%207.40.12%20AM.png

**Comment by ethgasstation** [comment]
I was reconfiguring a new server and it crashed when i was at work.  I think it is all fixed now.
