### ISSUE TITLE
API Documentation / units?

### ISSUE THREAD

**Issue by lightninglu10** [ethgasstation/ethgasstation-backend#5]
https://ethgasstation.info/json/ethgasAPI.json

Hey guys, I'm trying to use your adaptive oracle API, but can't figure out what Units they're in. It seems like 10x Gwei, but not 100%, can anyone confirm that these are the units? 70gwei for safe seems super high and right now it's 7 on the site.

**Comment by bamos01** [comment]
Hi - yes - they are definitely 10 gwei units - so divide by 10 to get in gwei- i know this is slightly confusing and probably will update in future

**Comment by nreilly** [comment]
If you do change it, can you please add it as a separate item in the JSON data set?

**Comment by lgn21st** [comment]
Can someone give us an explanation about why it need to divide by 10 here?

https://github.com/ethgasstation/ethgasstation/blob/4806b2bb4491156c59585ada0959f61e7b0ac32e/index.php#L118-L121

**Comment by 10a7** [comment]
@nreilly We're going to be deprecating the JSON data set in the future and moving to an actual API structure, so I don't believe we'll be making any more changes to the JSON data set at this time.

**Comment by xuanzhui** [comment]
Is there a online server hosting the api that can be called remotely?

**Comment by lakamsani** [comment]
possible alternative. https://api.etherscan.io/apis
