### ISSUE TITLE
Smart contract holding current price

### ISSUE THREAD

**Issue by fvictorio** [ethgasstation/ethgasstation-backend#9]
Hey, by any chance, do you have (or plan to have) a deployed smart contract that holds the last gas price and is updated by this oracle? Thanks.

**Comment by igorbarinov** [comment]
I'd like to add that we would like to sponsor gas spendings for the contract. Please contact me igor@poa.network or @igorbarinov on telegram
Thank you in advance

**Comment by 10a7** [comment]
Not sure if @ethgasstation wants one, but [I started work on one earlier today](https://github.com/10a7/eth-gas-burner) but haven't had a chance to get it actually tested/running yet. Feel free to issue some PRs and get something out there for yourself. I am never happy with my Solidity code.

**Comment by 10a7** [comment]
We're planning on doing this at some point, but before we do so we have some other issues that are taking precedence. In the meantime, you can deploy the repository above and update it from your own node.
